title: "My Homelab"
description: "My Projects"
markdown: kramdown


collections:
  posts:  # Blogs section
    output: true
  docs: # all docs files...
    output: true
  porjects: # Links to repo projects
    output: true
    